### ISSUE TITLE
TopologyException: found non-noded intersection between LINESTRING

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#184]
I try a simple sample and got a exception as below, hope anyone can give me a hint, thanks!
[Thread-1] INFO org.noise_planet.noisemodelling.emission.jdbc.LDENPointNoiseMapFactory$TableWriter - Exit TableWriter
**Exception in thread "main" org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING** ( -2.259876907416244E7 6348986.643063055, -2.2598765502816606E7 6348986.643063055 ) and LINESTRING ( -2.2598768864083268E7 6348973.618154722, -2.2598769074162435E7 6348986.643063055 ) [ (-2.2598769074162435E7, 6348986.643063055, NaN) ]
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:81)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:46)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.Geometry.intersection(Geometry.java:1354)
	at org.noise_planet.noisemodelling.propagation.jdbc.JdbcNoiseMap.fetchCellBuildings(JdbcNoiseMap.java:240)
	at org.noise_planet.noisemodelling.propagation.jdbc.PointNoiseMap.prepareCell(PointNoiseMap.java:96)
	at org.noise_planet.noisemodelling.propagation.jdbc.PointNoiseMap.evaluateCell(PointNoiseMap.java:187)
	at org.noiseplanet.nmtutorial01.Main.main(main.java:424)

**Comment by pierromond** [comment]
I think you have some problem with the input files. maybe you are using OSM ? sometimes buildings/grounds/roads are not well designed. A solution we use sometimes in this case is to download shp from geofabrik or bbbike. They are often less corrupted than those from osm.

**Comment by Tom119** [comment]
well, one simple solution: find the exact position and delete it from your shp file.

**Comment by whywayne2020** [comment]
thank all @pierromond @Tom119 ,I am using shp file. I think Tom's solution is woking. I have to manually check the model and find if two building's border overlap, that's really boring if there has thousand buildings. Hope anyone can programmly check this.
