### ISSUE TITLE
Calculate with Diffraction occur exception

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#226]
computeHorizontalDiffraction=true
and there has a exception(not every model)

relate: Find all buildings (polygons) that 2D cross the line p1->p2

[pool-56-thread-3] ERROR  propagation.**ComputeRays** - **side location conflict** [ (3722.0663246982026, -1214.5859549988606, 0.0) ]
org.locationtech.jts.geom.TopologyException: side location conflict [ (3722.0663246982026, -1214.5859549988606, 0.0) ]
	at org.locationtech.jts.geomgraph.EdgeEndStar.propagateSideLabels(EdgeEndStar.java:286)
	at org.locationtech.jts.geomgraph.EdgeEndStar.computeLabelling(EdgeEndStar.java:122)
	at org.locationtech.jts.operation.relate.RelateComputer.labelNodeEdges(RelateComputer.java:290)
	at org.locationtech.jts.operation.relate.RelateComputer.computeIM(RelateComputer.java:125)
	at org.locationtech.jts.operation.relate.RelateOp.getIntersectionMatrix(RelateOp.java:112)
	at org.locationtech.jts.operation.relate.RelateOp.relate(RelateOp.java:57)
	at org.locationtech.jts.geom.Geometry.relate(Geometry.java:1045)

cleanbuild seems not work.

**Comment by nicolas-f** [comment]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling version**
Version number of NoiseModelling you are using (ex 3.2)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by nicolas-f** [comment]
Related #224
