### ISSUE TITLE
With lastest clean building table V3.3.1 there still have exceptions

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#257]
version:NoiseModelling V3.3.1
❗ For some test case, the calcuation may occour Exception when not clean building table calcuation is OK.
For some test case, the calcuation may occour Exception when set computeHorizontalDiffraction and computeVerticalDiffraction on. But it's OK when not set on.

💡 FYI:
some exceptions may related to building models even after clean build table.
❌propagation.LayerPoly2Tri - Warning : hole rejected, can't find interior point.
❌Exception in thread "main" java.lang.RuntimeException: **Intersecting Constraints**
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.flipEdgeEvent(DTSweep.java:657)
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:631)
❌Exception in thread "main" java.lang.NullPointerException
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.isEdgeSideOfTriangle(DTSweep.java:543)
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:567)
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
	at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
❌[pool-12-thread-4] ERROR propagation.ComputeRays - side location conflict [ (-941.77, -2089.64, 0.0) ]
org.locationtech.jts.geom.TopologyException: side location conflict [ (-941.77, -2089.64, 0.0) ]

**Comment by nicolas-f** [comment]
Hi,

If you could provided a shape file or geojson with input buildings 300m around -941.77, -2089.64, 0.0 it would be helpfull.

Thanks

**Comment by whywayne2020** [comment]
Hi nicolas, I send a mail to Pierre (for I don't have you mail) with model occur with exception. Hope you can check it.thanks
