### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseModelling#45]
NPE while doing computation. With version d52d986f683875a7f6008e1f3b77babb1da84365
```
Caused by: java.lang.NullPointerException
    at org.orbisgis.noisemap.core.LayerJDelaunay.processDelaunay(LayerJDelaunay.java:279)
    at org.orbisgis.noisemap.core.LayerJDelaunay.processDelaunay(LayerJDelaunay.java:203)
    at org.orbisgis.noisemap.core.MeshBuilder.finishPolygonFeeding(MeshBuilder.java:335)
    at org.orbisgis.noisemap.core.MeshBuilder.finishPolygonFeeding(MeshBuilder.java:291)
    at org.orbisgis.noisemap.core.jdbc.PointNoiseMap.prepareCell(PointNoiseMap.java:79)
    at org.orbisgis.noisemap.core.jdbc.PointNoiseMap.evaluateCell(PointNoiseMap.java:157)
    at org.orbisgis.noisemap.h2.BR_PtGrid3D$PointRowSource.readRow(BR_PtGrid3D.java:198)
    at org.h2.tools.SimpleResultSet.next(SimpleResultSet.java:221)
```

**Comment by nicolas-f** [comment]
Replace

``` 
if(this.buildingWithID.get(potentialBuildingID).isTriangleInBuilding(triangle.getBarycenter())){
```

by

``` 
if(this.buildingWithID.get(potentialBuildingID) != null && this.buildingWithID.get(potentialBuildingID).isTriangleInBuilding(triangle.getBarycenter())){
```
