### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseModelling#463]
**NoiseModelling version**
4.X
**Describe the bug**
NoiseModelling throw an error. Maybe related to PR #462 
```
[pool-2-thread-43] ERROR - Index 34 out of bounds for length 34
Apr 14 08:59:58 plamade gradlew[2938715]: java.lang.IndexOutOfBoundsException: Index 34 out of bounds for length 34
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.Objects.checkIndex(Objects.java:372)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.ArrayList.remove(ArrayList.java:536)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.computeHEdgeDiffraction(ComputeCnossosRays.java:741)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.directPath(ComputeCnossosRays.java:319)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.directPath(ComputeCnossosRays.java:297)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.rcvSrcPropagation(ComputeCnossosRays.java:272)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.computeRaysAtPosition(ComputeCnossosRays.java:231)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays$RangeReceiversComputation.run(ComputeCnossosRays.java:1652)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.lang.Thread.run(Thread.java:829)
Apr 14 08:59:58 plamade gradlew[2938715]: Exception in thread "pool-2-thread-43" java.lang.IndexOutOfBoundsException: Index 34 out of bounds for length 34
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.Objects.checkIndex(Objects.java:372)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.ArrayList.remove(ArrayList.java:536)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.computeHEdgeDiffraction(ComputeCnossosRays.java:741)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.directPath(ComputeCnossosRays.java:319)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.directPath(ComputeCnossosRays.java:297)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.rcvSrcPropagation(ComputeCnossosRays.java:272)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays.computeRaysAtPosition(ComputeCnossosRays.java:231)
Apr 14 08:59:58 plamade gradlew[2938715]:         at org.noise_planet.noisemodelling.pathfinder.ComputeCnossosRays$RangeReceiversComputation.run(ComputeCnossosRays.java:1652)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 14 08:59:58 plamade gradlew[2938715]:         at java.base/java.lang.Thread.run(Thread.java:829)
```
@SPalominos

**Comment by pierromond** [comment]
Indeed !

![image](https://user-images.githubusercontent.com/1659842/163380392-c454ce13-a222-47c3-b666-8bdfa175cd3a.png)
