### ISSUE TITLE
Problem Using data from OpenStreetMap

### ISSUE THREAD

**Issue by zonndjay** [Ifsttar/NoiseModelling#48]
Bonjour,
En suivant le tutoriel "Using data from OpenStreetMap", j'ai cette erreur ::

ERROR [Thread-141] (ExecuteScriptProcess.java:160) - General error: "java.lang.NullPointerException"; SQL statement:
create table tri_lvl as SELECT * from
BR_TriGrid((select st_expand(st_envelope(st_accum(the_geom)), -750, - 750) the_geom from ROADS_SRC),'buildings','roads_src','DB_M','',750,50,1.5,2.8,75,0,0,0.23) [50000-182]
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException"; SQL statement:
create table tri_lvl as SELECT * from
BR_TriGrid((select st_expand(st_envelope(st_accum(the_geom)), -750, - 750) the_geom from ROADS_SRC),'buildings','roads_src','DB_M','',750,50,1.5,2.8,75,0,0,0.23) [50000-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.command.Command.executeUpdate(Command.java:262)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2gis.utilities.wrapper.StatementWrapper.execute(StatementWrapper.java:93)
	at org.orbisgis.view.sqlconsole.actions.ExecuteScriptProcess.parseAndExecuteScript(ExecuteScriptProcess.java:125)
	at org.orbisgis.view.sqlconsole.actions.ExecuteScriptProcess.run(ExecuteScriptProcess.java:154)
	at org.orbisgis.view.background.Job.run(Job.java:87)
	at org.orbisgis.view.background.RunnableBackgroundJob.run(RunnableBackgroundJob.java:71)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.orbisgis.noisemap.core.jdbc.TriangleNoiseMap.evaluateCell(TriangleNoiseMap.java:291)
	at org.orbisgis.noisemap.h2.BR_TriGrid3D$TriangleRowSource.readRow(BR_TriGrid3D.java:275)
	at org.h2.tools.SimpleResultSet.next(SimpleResultSet.java:221)
	at org.h2.result.LocalResult.read(LocalResult.java:97)
	at org.h2.table.FunctionTable.getResult(FunctionTable.java:197)
	at org.h2.index.FunctionIndex.find(FunctionIndex.java:48)
	at org.h2.index.BaseIndex.find(BaseIndex.java:127)
	at org.h2.index.IndexCursor.find(IndexCursor.java:159)
	at org.h2.table.TableFilter.next(TableFilter.java:329)
	at org.h2.command.dml.Select.queryFlat(Select.java:532)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:644)
	at org.h2.command.dml.Query.query(Query.java:322)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:185)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	... 8 more

De plus, comment récupérer les données réelles du trafic routier d'un lieu ? Que fait on lorsqu'on utilise le "Fake traffic"?

Cordialement

**Comment by nicolas-f** [comment]
Bonjour,

Il est possible que la zone ne soit pas assez grande. Dans ce cas l’enveloppe de calcul créé par

```sql
 st_expand(st_envelope(st_accum(the_geom)), -750, - 750)
```

n'est pas assez grande.

Vous pouvez donc remplacer simplement par 

```sql
st_envelope(st_accum(the_geom)
```

Pour vérifier cela vous pouvez essayer de visualiser la zone de calcul comme ceci:

```
create table zonecalcul as select st_expand(st_envelope(st_accum(the_geom)), -750, - 750) the_geom from ROADS_SRC;
```

et le placer dans le toc.

> comment récupérer les données réelles du trafic routier d'un lieu

Il n'y a pas à notre connaissance de base de données de trafic routier pour toute les voies.

> Que fait on lorsqu'on utilise le "Fake traffic"?

Ce sont des valeurs arbitraires de vitesse et de trafic qui sont appliquées en fonction de la valeur du tag 'highway' d'open street map.

**Comment by zonndjay** [comment]
Bonjour, 
Votre solution fonctionne à merveille. Merci.

Cordialement.
