### ISSUE TITLE
Importing shpfiles in python

### ISSUE THREAD

**Issue by andredaa** [Ifsttar/NoiseModelling#69]
Trying to import shape files in python does not work for me.
Using shpread I get the following error: 
Caught this error: OperationalError('server closed the connection unexpectedly
This probably means the server terminated abnormally
tbefore or while processing the request.

Server trace: 
 
CALL SHPREAD('/home/USER/orbisgis_noise/orbisgis_h2gis/input_shape/buildings_shp/buildings.shp', 'buildings');
org.h2.jdbc.JdbcSQLException: 
General error: "java.lang.NullPointerException" [50000-182]; SQL statement:

               CALL SHPREAD('/home/USER/orbisgis_noise/orbisgis_h2gis/input_shape/buildings_shp/buildings.shp', 'buildings') [0-182]
        at org.h2.message.DbException.addSQL(DbException.java:132)
        at org.h2.command.Command.executeQuery(Command.java:213)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:179)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
        at org.h2.server.pg.PgServerThread.process(PgServerThread.java:392)
        at org.h2.server.pg.PgServerThread.run(PgServerThread.java:90)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: 

***

Using filetable there is no error - a table is created but remains empty. 

***
Importing a shpFile through the browser interface works - however if I want to connect to that database then - the connection fails. I assume this is some spatial plugin issue?
org.h2.jdbc.JdbcSQLException: Class "org.h2gis.functions.spatial.properties.ST_GeometryTypeCode" not found; SQL statement:
CREATE DOMAIN POINT AS GEOMETRY(1) CHECK (PUBLIC.ST_GEOMETRYTYPECODE(VALUE) = 1) [90086-182]

***

One more question: Is there a possibility to open the resulting databases in OrbisGis or the H2 webinterface? I cannnot connect the webinterface to an existing database - it always seems to create a new one on the fly , when trying to connect to existing database on the browserinterface-

***
I would be very happy about any tipps !:)

**Comment by nicolas-f** [comment]
Have you followed the tutorial https://github.com/Ifsttar/NoiseModelling/wiki/11-Scripting-with-Python

Does it run without errors ?

**Comment by andredaa** [comment]
the tutorial runs without errors. However, when importing a shapefile for the buildings, instead of creating mock building via SQL commands, this happens:
CALL SHPREAD('/home/USER/orbisgis_noise/orbisgis_h2gis/input_shape/buildings_shp/buildings.shp', 'buildings');
org.h2.jdbc.JdbcSQLException:
General error: "java.lang.NullPointerException" [50000-182]; SQL statement:

           CALL SHPREAD('/home/USER/orbisgis_noise/orbisgis_h2gis/input_shape/buildings_shp/buildings.shp', 'buildings') [0-182]
    at org.h2.message.DbException.addSQL(DbException.java:132)
    at org.h2.command.Command.executeQuery(Command.java:213)
    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:179)
    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
    at org.h2.server.pg.PgServerThread.process(PgServerThread.java:392)
    at org.h2.server.pg.PgServerThread.run(PgServerThread.java:90)
    at java.lang.Thread.run(Thread.java:748)



Thanks for your help"

**Comment by qhesry** [comment]
Hi !

I've updated the tutorial for the last version of NoiseModelling released.

I've tested to use 'Call SPHREAD', and 'CALL TABLE_FILE' too. And it worked after I've removed the line "create table buildings ( the_geom GEOMETRY );" in the python script.

Can you try this and test again ?

**Comment by andredaa** [comment]
Hello @qhesry !
Thank you for the update on the tutorial!
I've tested using Call SHPHREAD and it did not complain ;)
However the created tables seem to stay empty as I get a nullpointer exception later. 
Is there a way to  investigate the contents of the database created?
Is there a possibility to open the resulting databases in OrbisGis or the H2 webinterface? 
I cannnot connect the webinterface to an existing database. It always seems to create a new one on the fly with the same name.
Opening OrbisGis and importing the database results in an error to: could not find interpreter. 

Thanks for your help!

**Comment by andredaa** [comment]
maybe there is something wrong with my shapefile. would you be able to provide your test shp file?
Thank you!

**Comment by andredaa** [comment]
CALL SHPREAD('/home/andre/noise_new/orbisgis-noisemodelling-2018-07-18/input_shape/buildings_shp/buildings.shp', 'buildings');
org.h2.jdbc.JdbcSQLException: 
General error: "java.lang.NullPointerException" [50000-197]; SQL statement:

        CALL SHPREAD('/home/andre/noise_new/orbisgis-noisemodelling-2018-07-18/input_shape/buildings_shp/buildings.shp', 'buildings') [0-197]
        at org.h2.message.DbException.addSQL(DbException.java:133)
        at org.h2.command.Command.executeQuery(Command.java:220)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
        at org.h2.server.pg.PgServerThread.process(PgServerThread.java:423)
        at org.h2.server.pg.PgServerThread.run(PgServerThread.java:100)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException:

**Comment by pierromond** [comment]
https://noisemodelling.readthedocs.io/en/latest/NoiseModellingScripting.html
