### ISSUE TITLE
BR_TriGrid fails for certain building constellations

### ISSUE THREAD

**Issue by andredaa** [Ifsttar/NoiseModelling#75]
Our script is using your python-script (https://github.com/Ifsttar/NoiseModelling/wiki/11-Scripting-with-Python) in order to assess the noise emitted by a highway into a virtual neighborhood. See screenshot. Urban planners can provide different constellations of buildings and see the effect of building constellation onto the noise propagation. The script worked fine for many constellations of buildings. However for some constellations of buildings it fails.

![](https://user-images.githubusercontent.com/4631906/60264964-c1a08a00-98e4-11e9-802e-b82926dee97b.png)

**If I put a building into the marked vacant gridcell, the script runs fine. Leaving the space "free" (no building, no road) , I get the error.** 
Shortest distance from marked square to road should be roughly 515meters. One square is 16*16meters.

Could you help me understanding , why the BR_TriGrid fails? We would like to automatically assess different virtual neighborhood designs.

For reproducing the error, I created a branch of the script here. 
You can reproduce the buildings from [this ](https://github.com/CityScope/CSL_Hamburg_Noise/blob/buildings-error/debugging/building_insert_queries)
You can reproduce roads, traffic from [this  ](https://github.com/CityScope/CSL_Hamburg_Noise/blob/buildings-error/debugging/road_traffic_insert_queries)
You can look at the **stack-trace** (as much as I managed to get out of it) [here](https://github.com/CityScope/CSL_Hamburg_Noise/blob/buildings-error/debugging/sql_log)

There is nothing in .OrbisGis/5.1/orbisgis.log ; I guess because the OrbisGis package from https://github.com/Ifsttar/NoiseModelling/wiki/11-Scripting-with-Python works differently)

Thank you so much!

**Comment by andredaa** [comment]
You can reproduce the script by starting the orbisgis server by running
` java -cp "bin/*:bundle/*:sys-bundle/*" org.h2.tools.Server -pg -trace` inside the project folder

Then execute noisemap.py 

The script will fail with the aforementioned issue. Uncomment these lines to add a building in the marked gridcell and the script will run fine. https://github.com/CityScope/CSL_Hamburg_Noise/blob/7d97297ade14485051de3fe8888f3deddcf7de1f/noisemap.py#L42

**Comment by Picaut** [comment]
Than you very much.
We will take a look and come back as soon as possible.
Best regards

**Comment by nicolas-f** [comment]
Hi,

The submodule city_io_to_geojson is missing.

**Comment by nicolas-f** [comment]
As a side note
I think it should be way more efficient to import data using h2gis drivers:
http://www.h2gis.org/docs/1.5.0/SHPRead/
http://www.h2gis.org/docs/1.5.0/GeoJsonRead/

**Comment by andredaa** [comment]
Hi, 
thank you so much for your quick reply! 

If the submodule "city_io_to_geojson" is not loaded correctly - it was because I missed the .gitmodules file. It is pushed now. You can checkout the branch "buildings-error" from  https://github.com/CityScope/CSL_Hamburg_Noise and Pull. You can init the submodule with git submodule init and git submodule update .

Start the database server by executing 

> java -cp "bin/*:bundle/*:sys-bundle/*" org.h2.tools.Server -pg -trace

then run 
> python noisemap.py

(it's python 2.7)


The script will fail with the aforementioned issue. Uncomment these lines to add a building in the marked gridcell and the script will run fine. https://github.com/CityScope/CSL_Hamburg_Noise/blob/7d97297ade14485051de3fe8888f3deddcf7de1f/noisemap.py#L42

Thanks for your hint on the GEOJSONREAD - I will look into it.

**Comment by nicolas-f** [comment]
NoiseModelling is executing a Constrained Delaunay mesh of your buildings.

The problem here is that the walls of your buildings are intersecting. It is possible to merge buildings that may be problematic with this operation: 

```sql
drop table if exists BUILDINGS_SIMP_MERGE;
create table BUILDINGS_SIMP_MERGE as select ST_UNION(ST_SIMPLIFYPRESERVETOPOLOGY(ST_buffer(ST_ACCUM(the_geom),0),0.1)) the_geom from buildings;
drop table if exists buildings;
create table buildings(id serial, the_geom polygon) as select null, the_geom from st_explode('BUILDINGS_SIMP_MERGE');
drop table BUILDINGS_SIMP_MERGE;
```
You do not set an height for your buildings, is this expected ?

```java
org.h2.jdbc.JdbcSQLException: Erreur générale: "java.lang.NullPointerException"
General error: "java.lang.NullPointerException"; SQL statement:

    create table tri_lvl as SELECT * from
    BR_TriGrid((select st_expand(st_envelope(st_accum(the_geom)), 750, 750) the_geom from ROADS_SRC),'buildings','roads_src','DB_M','',750,50,1.5,2.8,75,0,0,0.23) [50000-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convert(DbException.java:307)
        at org.h2.command.Command.executeUpdate(Command.java:274)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
        at org.h2.server.pg.PgServerThread.process(PgServerThread.java:423)
        at org.h2.server.pg.PgServerThread.run(PgServerThread.java:100)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.isEdgeSideOfTriangle(DTSweep.java:543)
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:567)
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:348)
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.sweep(DTSweep.java:110)
        at org.poly2tri.triangulation.delaunay.sweep.DTSweep.triangulate(DTSweep.java:72)
        at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:108)
        at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:98)
        at org.orbisgis.noisemap.core.LayerPoly2Tri.processDelaunay(LayerPoly2Tri.java:214)
        at org.orbisgis.noisemap.core.MeshBuilder.finishPolygonFeeding(MeshBuilder.java:317)
        at org.orbisgis.noisemap.core.jdbc.TriangleNoiseMap.computeDelaunay(TriangleNoiseMap.java:213)
        at org.orbisgis.noisemap.core.jdbc.TriangleNoiseMap.evaluateCell(TriangleNoiseMap.java:274)
        at org.orbisgis.noisemap.h2.BR_TriGrid3D$TriangleRowSource.readRow(BR_TriGrid3D.java:275)
        at org.h2.tools.SimpleResultSet.next(SimpleResultSet.java:222)
        at org.h2.result.LocalResult.read(LocalResult.java:106)
        at org.h2.table.FunctionTable.getResult(FunctionTable.java:197)
        at org.h2.index.FunctionIndex.find(FunctionIndex.java:54)
        at org.h2.index.BaseIndex.find(BaseIndex.java:131)
        at org.h2.index.IndexCursor.find(IndexCursor.java:175)
        at org.h2.table.TableFilter.next(TableFilter.java:471)
        at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1453)
        at org.h2.result.LazyResult.hasNext(LazyResult.java:79)
        at org.h2.result.LazyResult.next(LazyResult.java:59)
        at org.h2.command.dml.Select.queryFlat(Select.java:527)
        at org.h2.command.dml.Select.queryWithoutCache(Select.java:633)
        at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
        at org.h2.command.dml.Query.query(Query.java:371)
        at org.h2.command.dml.Insert.insertRows(Insert.java:202)
        at org.h2.command.dml.Insert.update(Insert.java:134)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:134)
        at org.h2.command.CommandContainer.update(CommandContainer.java:102)
        at org.h2.command.Command.executeUpdate(Command.java:261)

```

**Comment by andredaa** [comment]
Thank you so much for your tip. I will merge the buildings as suggested and try again. 
I am a bit unclear on the handling of building height and actually wondered about this. 
I was following mostly this paper, where it says the buidlings are a 2D geometry without information about height or topography. (https://github.com/CityScope/CSL_Hamburg_Noise/blob/buildings-error/documentation/literature/ifsttar.pdf, page 13)
Could you quickly link me to an explanation of the handling of building heights?

**Comment by nicolas-f** [comment]
Some tutorials cover buildings with height.

Technically it is an additional numeric field named "HEIGHT" in the buildings table.

Then this function must be used with the appropriate attributes:
https://github.com/Ifsttar/NoiseModelling/wiki/03-SQL-functions#br_trigrid3d

A tutorial with buildings with height:
https://github.com/Ifsttar/NoiseModelling/wiki/05-Ground-effect
https://github.com/Ifsttar/NoiseModelling/wiki/06-Modelling-barrier-using-digital-elevation-model
https://github.com/Ifsttar/NoiseModelling/wiki/08-Vertical-noise-map

As you "generate" the buildings, it should be appropriate to set a free space (at least 10cm) between buildings instead of trying to fix faulty polygons.

**Comment by andredaa** [comment]
Looks like it was the intersecting buildings that caused the problem. 
I recreated the buildings table like this though

>   **--** create table buildings(**id serial**, the_geom polygon) as select null, the_geom from st_explode('BUILDINGS_SIMP_MERGE');
>        **create table buildings(the_geom GEOMETRY) as select the_geom from st_explode('BUILDINGS_SIMP_MERGE');**

As it failed when creating it with a id column.

**Comment by andredaa** [comment]
> As you "generate" the buildings, it should be appropriate to set a free space (at least 10cm) between buildings instead of trying to fix faulty polygons.

Yes, we adjust it so that we can put space in between seperate buildings and merge polygons for buildings stretching over several grid cells. 

Thank you so much for your explanation of the 3D function. I will look into it.

**Comment by andredaa** [comment]
Thank you very much for your support and prompt answers!
